name: TF reusable yaml

on:
  push:
    branches:
      - feature

jobs:
  call-security-scan:
    uses: yrneh10/testrun/.github/workflows/nodereusable.yml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
