name: Call Reusable Snyk CICD Scan

on:
  push:
    branches:
      - feature
  workflow_dispatch:      
#testnow
jobs:
  call-security-scan:
    uses: yrneh10/testrun/.github/workflows/nodereusable.yml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
