name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Snyk Code Test (fail only if critical)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          # Run Snyk Code test and save JSON output
          snyk code test --json > snyk-code.json || true
      
          # Extract critical count safely (handle null or empty vulnerabilities)
          CRITICAL_COUNT=$(jq '[.vulnerabilities // [] | .[] | select(.severity == "critical")] | length' snyk-code.json)
      
          echo "Critical issues found: $CRITICAL_COUNT"
      
          # Fail the build only if criticals are present
          if [ "$CRITICAL_COUNT" -gt 0 ]; then
            echo "❌ Failing due to critical vulnerabilities"
            exit 1
          else
            echo "✅ No critical issues — build passes"
          fi  
          snyk monitor --all-projects

      - name: Run Snyk CLI SCA & Monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test 
          snyk monitor --all-projects          
          
