name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Snyk Code Test (fail only if critical)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          # Run test and save all issues
          snyk code test --json > snyk-code.json || true
      
          # Print summary (optional)
          cat snyk-code.json | jq '[.vulnerabilities[] | {severity, id, title}]'
      
          # Count criticals
          CRITICAL_COUNT=$(jq '[.vulnerabilities[] | select(.severity == "critical")] | length' snyk-code.json)
      
          echo "Critical issues found: $CRITICAL_COUNT"
      
          # Fail only if critical issues exist
          if [ "$CRITICAL_COUNT" -gt 0 ]; then
            echo "❌ Failing the build due to critical vulnerabilities"
            exit 1
          else
            echo "✅ No critical issues — build passes"
          fi        
          snyk monitor --all-projects

      - name: Run Snyk CLI SCA & Monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test 
          snyk monitor --all-projects          
          
